 local menue0e4fc6213e8b3593495a7260c3a4c2e = {
     {"Onboard", "onboard", "/usr/share/icons/hicolor/16x16/apps/onboard.png" },
 }

 local menu98edb85b00d9527ad5acebe451b3fae6 = {
     {"Atom", "env ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false /usr/bin/atom ", "/usr/share/icons/hicolor/16x16/apps/atom.png" },
     {"Boostnote", "boostnote ", "/usr/share/pixmaps/boostnote.png" },
     {"Character Map", "gucharmap", "/usr/share/icons/gnome/16x16/apps/accessories-character-map.png" },
     {"CopyQ", "copyq", "/usr/share/icons/hicolor/16x16/apps/copyq.png" },
     {"Disks", "gnome-disks"},
     {"Double Commander", "doublecmd ", "/usr/share/pixmaps/doublecmd.png" },
     {"Firejail Configuration Wizard", "firejail-ui", "/usr/share/pixmaps/firejail-ui.png" },
     {"Font Finder", "fontfinder-gtk"},
     {"Fonts", "gnome-font-viewer "},
     {"Galculator", "galculator", "/usr/share/icons/hicolor/48x48/apps/galculator.png" },
     {"Godot", "/usr/bin/godot ", "/usr/share/icons/hicolor/16x16/apps/godot.png" },
     {"KeePassXC", "keepassxc ", "/usr/share/icons/hicolor/256x256/apps/keepassxc.png" },
     {"Lifeograph", "lifeograph ", "/usr/share/icons/hicolor/16x16/apps/net.sourceforge.Lifeograph.png" },
     {"Main Menu", "alacarte", "/usr/share/icons/hicolor/16x16/apps/alacarte.png" },
     {"NFO Viewer", "nfoview "},
     {"Neovim", "xterm -e nvim ", "/usr/share/pixmaps/nvim.png" },
     {"Neovim-Qt", "nvim-qt -- ", "/usr/share/icons/hicolor/192x192/apps/nvim-qt.png" },
     {"NixNote2", "nixnote2", "/usr/share/icons/hicolor/48x48/apps/nixnote2.png" },
     {"Onboard", "onboard", "/usr/share/icons/hicolor/16x16/apps/onboard.png" },
     {"Passwords and Keys", "seahorse"},
     {"Postman", "postman ", "/usr/share/icons/hicolor/128x128/apps/postman.png" },
     {"Redshift", "redshift-gtk"},
     {"Screenshot", "gnome-screenshot --interactive"},
     {"SysMonitor", "sysmon", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"Variety", "variety "},
     {"Vim", "xterm -e vim ", "/usr/share/icons/hicolor/48x48/apps/gvim.png" },
     {"Visual Studio Code", "/opt/visual-studio-code/code --no-sandbox --unity-launch ", "/usr/share/icons/visual-studio-code.png" },
     {"compton", "compton", "/usr/share/icons/hicolor/48x48/apps/compton.png" },
     {"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
     {"picom", "picom"},
     {"wxHexEditor", "wxHexEditor", "/usr/share/pixmaps/wxHexEditor.png" },
     {"xgps", "xgps"},
     {"xgpsspeed", "xgpsspeed"},
 }

 local menu78059f1898ed518c6ccd6a6392fa82c1 = {
     {"AUR", "xdg-open https://aur.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Bugs", "xdg-open https://bugs.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Developers", "xdg-open http://www.archlinux.org/developers/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Documentation", "xdg-open https://wiki.archlinux.org/index.php/Official_Arch_Linux_Install_Guide", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Donate", "xdg-open http://www.archlinux.org/donate/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Forum", "xdg-open https://bbs.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Homepage", "xdg-open http://www.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"SVN", "xdg-open http://projects.archlinux.org/svntogit/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Schwag", "xdg-open http://www.zazzle.com/archlinux/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
     {"Wiki", "xdg-open https://wiki.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
 }

 local menude7a22a0c94aa64ba2449e520aa20c99 = {
     {"BibleTime ", "bibletime"},
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"Stellarium", "stellarium --startup-script=", "/usr/share/icons/hicolor/16x16/apps/stellarium.png" },
     {"Xiphos Bible Guide", "xiphos"},
 }

 local menu251bd8143891238ecedc306508e29017 = {
     {"AstroMenace", "astromenace", "/usr/share/pixmaps/astromenace.png" },
     {"DeSmuME (Gtk)", "desmume", "/usr/share/pixmaps/DeSmuME.xpm" },
     {"Dolphin Emulator", "env QT_QPA_PLATFORM=xcb dolphin-emu", "/usr/share/icons/hicolor/256x256/apps/dolphin-emu.png" },
     {"Godot", "/usr/bin/godot ", "/usr/share/icons/hicolor/16x16/apps/godot.png" },
     {"PCSX2", "env GDK_BACKEND=x11 __GL_THREADED_OPTIMIZATIONS=1 mesa_glthread=true MESA_NO_ERROR=1 PCSX2", "/usr/share/pixmaps/PCSX2.xpm" },
     {"VDrift", "vdrift", "/usr/share/icons/hicolor/16x16/apps/vdrift.png" },
 }

 local menud334dfcea59127bedfcdbe0a3ee7f494 = {
     {"Archi", "/usr/bin/archi", "/usr/share/pixmaps/archi.xpm" },
     {"Darktable", "/usr/bin/darktable ", "/usr/share/icons/hicolor/16x16/apps/darktable.png" },
     {"E-book viewer", "ebook-viewer --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-viewer.png" },
     {"Flameshot", "flameshot", "/usr/share/icons/hicolor/48x48/apps/org.flameshot.Flameshot.png" },
     {"GNU Image Manipulation Program", "gimp-2.10 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/org.inkscape.Inkscape.png" },
     {"LRF viewer", "lrfviewer ", "/usr/share/icons/hicolor/16x16/apps/calibre-viewer.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Mandelbulber-OpenCL", "mandelbulber-opencl", "///usr/share/mandelbulber/icons/mandelbulber.png" },
     {"PDF Editor", "pdfedit", "///usr/share/pdfedit/icon/pdfedit_logo.png" },
     {"Pencil", "/usr/bin/pencil ", "/usr/share/icons/hicolor/16x16/apps/pencil.png" },
     {"QtQR", "qtqr "},
     {"Shotwell", "shotwell ", "/usr/share/icons/hicolor/16x16/apps/shotwell.png" },
     {"XDvi", "xdvi "},
     {"gThumb", "gthumb ", "/usr/share/icons/hicolor/16x16/apps/org.gnome.gThumb.png" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Avahi SSH Server Browser", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC Server Browser", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Chromium", "/usr/bin/chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"Crow Translate", "crow", "/usr/share/icons/hicolor/16x16/apps/crow-translate.png" },
     {"ELinks", "xterm -e /usr/bin/elinks ", "/usr/share/icons/gnome/16x16/mimetypes/html.png" },
     {"ElectronPlayer", "electronplayer "},
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Firefox Developer Edition", "/usr/lib/firefox-developer-edition/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox-developer-edition.png" },
     {"Google Chrome", "/usr/bin/google-chrome-stable ", "/usr/share/icons/hicolor/16x16/apps/google-chrome.png" },
     {"MEGAsync", "megasync", "/usr/share/icons/hicolor/16x16/apps/mega.png" },
     {"NixNote2", "nixnote2", "/usr/share/icons/hicolor/48x48/apps/nixnote2.png" },
     {"Opera", "opera ", "/usr/share/icons/hicolor/16x16/apps/opera.png" },
     {"Popcorn Time", "popcorntime ", "/usr/share/icons/hicolor/256x256/apps/popcorntime.png" },
     {"Rambox Pro", "/opt/ramboxpro/ramboxpro --no-sandbox ", "/usr/share/icons/hicolor/16x16/apps/ramboxpro.png" },
     {"Signal", "signal-desktop -- ", "/usr/share/icons/hicolor/16x16/apps/signal-desktop.png" },
     {"Skype", "/usr/bin/skypeforlinux ", "/usr/share/icons/hicolor/16x16/apps/skypeforlinux.png" },
     {"Syncthing GTK", "syncthing-gtk", "/usr/share/icons/hicolor/16x16/apps/syncthing-gtk.png" },
     {"TigerVNC Viewer", "/usr/bin/vncviewer", "/usr/share/icons/hicolor/16x16/apps/tigervnc.png" },
     {"Tor Browser (en-US)", "/usr/bin/tor-browser ", "/usr/share/pixmaps/tor-browser.png" },
     {"Waterfox G3", "waterfox-g3 ", "/usr/share/icons/hicolor/16x16/apps/waterfox-g3.png" },
     {"Wireshark", "wireshark ", "/usr/share/icons/hicolor/16x16/apps/wireshark.png" },
     {"Zoom", "/usr/bin/zoom ", "/usr/share/pixmaps/Zoom.png" },
     {"qBittorrent", "qbittorrent ", "/usr/share/icons/hicolor/16x16/apps/qbittorrent.png" },
     {"uGet", "env GDK_BACKEND=x11 uget-gtk ", "/usr/share/icons/hicolor/16x16/apps/uget-icon.png" },
     {"wpa_gui", "wpa_gui", "/usr/share/pixmaps/wpa_gui.svg" },
 }

 local menudf814135652a5a308fea15bff37ea284 = {
     {"Calibre", "calibre --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-gui.png" },
     {"Crow Translate", "crow", "/usr/share/icons/hicolor/16x16/apps/crow-translate.png" },
     {"E-book editor", "ebook-edit --detach ", "/usr/share/icons/hicolor/16x16/apps/calibre-ebook-edit.png" },
     {"GitQlient", "gitqlient", "/usr/share/icons/hicolor/16x16/apps/gitqlient.png" },
     {"Joplin", "/usr/bin/joplin-desktop", "///usr/share/joplin-desktop/resources/build/icons/128x128.png" },
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Master PDF Editor", "/opt/master-pdf-editor-4/masterpdfeditor4 ", "///opt/master-pdf-editor-4/masterpdfeditor4.png" },
     {"PDF Chain", "pdfchain", "/usr/share/icons/hicolor/16x16/apps/pdfchain.png" },
     {"PDF Decryptor", "xterm -e /usr/bin/pdf-decrypt ", "///usr/share/pixmaps/pdf-decrypt.png" },
     {"WPS 2019", "/usr/bin/wps ", "/usr/share/icons/hicolor/16x16/apps/wps-office2019-kprometheus.png" },
     {"WPS PDF", "/usr/bin/wpspdf ", "/usr/share/icons/hicolor/16x16/apps/wps-office2019-pdfmain.png" },
     {"WPS Presentation", "/usr/bin/wpp ", "/usr/share/icons/hicolor/16x16/apps/wps-office2019-wppmain.png" },
     {"WPS Spreadsheets", "/usr/bin/et ", "/usr/share/icons/hicolor/16x16/apps/wps-office2019-etmain.png" },
     {"WPS Writer", "/usr/bin/wps ", "/usr/share/icons/hicolor/16x16/apps/wps-office2019-wpsmain.png" },
     {"Xournal++", "xournalpp "},
     {"qpdfview", "qpdfview --unique "},
 }

 local menu6311ae17c1ee52b36e68aaf4ad066387 = {
     {"Bible Analyzer 5.2", "python2 -u /opt/bibleanalyzer/ba-run.py", "/usr/share/icons/bibleanalyzer.png" },
     {"Bible Analyzer User Manual", "firefox /opt/bibleanalyzer/manual/index.html"},
     {"Google Meets", "/usr/bin/google-meet-desktop"},
     {"Scratch 3", "scratch3 ", "/usr/share/icons/hicolor/72x72/apps/scratch3.png" },
 }

 local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
     {"Apache NetBeans", "netbeans ", "/usr/share/pixmaps/netbeans.png" },
     {"Atom", "env ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false /usr/bin/atom ", "/usr/share/icons/hicolor/16x16/apps/atom.png" },
     {"Boostnote", "boostnote ", "/usr/share/pixmaps/boostnote.png" },
     {"CMake", "cmake-gui ", "/usr/share/icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"Code::Blocks IDE", "codeblocks ", "/usr/share/icons/hicolor/64x64/apps/codeblocks.png" },
     {"CoqIDE Proof Assistant", "coqide", "/usr/share/pixmaps/coqide.png" },
     {"D-Feet", "d-feet"},
     {"DBeaver Community", "dbeaver", "/usr/share/icons/hicolor/16x16/apps/dbeaver.png" },
     {"Eclipse", "eclipse", "/usr/share/icons/hicolor/16x16/apps/eclipse.png" },
     {"Electron", "electron ", "/usr/share/pixmaps/electron.png" },
     {"Electron 11", "electron11 ", "/usr/share/pixmaps/electron11.png" },
     {"FLUID", "fluid ", "/usr/share/icons/hicolor/32x32/apps/fluid.png" },
     {"Fiddler Web Debugger Proxy", "mono /opt/fiddler/Fiddler.exe ", "/usr/share/pixmaps/fiddler.png" },
     {"Genymotion", "/usr/bin/genymotion", "///opt/genymotion/icons/icon.png" },
     {"Genymotion Player", "/usr/bin/genymotion-player"},
     {"GitAhead", "gitahead", "/usr/share/icons/hicolor/16x16/apps/gitahead.png" },
     {"Gluon Scene Builder 11", "scene-builder", "/usr/share/pixmaps/scene-builder.png" },
     {"Insomnia Designer", "\"/opt/Insomnia Designer/insomnia-designer\" ", "/usr/share/icons/hicolor/16x16/apps/insomnia-designer.png" },
     {"Meld", "meld ", "/usr/share/icons/hicolor/16x16/apps/org.gnome.meld.png" },
     {"Modelio", "/opt/modelio/modelio.sh ", "///opt/modelio/icon.xpm" },
     {"Pencil", "/usr/bin/pencil ", "/usr/share/icons/hicolor/16x16/apps/pencil.png" },
     {"Postman", "postman ", "/usr/share/icons/hicolor/128x128/apps/postman.png" },
     {"Qt Assistant", "assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "designer ", "/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "linguist ", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"React Native Debugger", "react-native-debugger", "/usr/share/pixmaps/react-native-debugger.png" },
     {"Visual Studio Code", "/opt/visual-studio-code/code --no-sandbox --unity-launch ", "/usr/share/icons/visual-studio-code.png" },
     {"ZeroBrane Studio", "zbstudio ", "/usr/share/icons/hicolor/16x16/apps/zbstudio.png" },
     {"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
     {"qgit", "qgit", "/usr/share/icons/hicolor/48x48/apps/qgit.png" },
     {"r2cutter", "r2cutter"},
     {"wxLua Editor", "wxLua ", "/usr/share/icons/wxlualogo.xpm" },
 }

 local menu80d754c83abbbd4ef5d150904efcc86c = {
     {"CoqIDE Proof Assistant", "coqide", "/usr/share/pixmaps/coqide.png" },
     {"Mandelbulber-OpenCL", "mandelbulber-opencl", "///usr/share/mandelbulber/icons/mandelbulber.png" },
 }

 local menu52dd1c847264a75f400961bfb4d1c849 = {
     {"Cheese", "cheese"},
     {"Ex Falso", "exfalso", "/usr/share/icons/hicolor/16x16/apps/io.github.quodlibet.ExFalso.png" },
     {"MuseScore 3.6", "mscore ", "/usr/share/icons/hicolor/16x16/apps/mscore.png" },
     {"OpenShot Video Editor", "openshot-qt ", "/usr/share/icons/hicolor/64x64/apps/openshot-qt.png" },
     {"Popcorn Time", "popcorntime ", "/usr/share/icons/hicolor/256x256/apps/popcorntime.png" },
     {"PulseAudio System Tray", "pasystray", "/usr/share/pixmaps/pasystray.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"Qt V4L2 video capture utility", "qvidcap", "/usr/share/icons/hicolor/16x16/apps/qvidcap.png" },
     {"Quod Libet", "quodlibet --run --play-file ", "/usr/share/icons/hicolor/16x16/apps/io.github.quodlibet.QuodLibet.png" },
     {"Shortwave", "shortwave"},
     {"VLC media player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"Webcamoid", "webcamoid", "/usr/share/icons/hicolor/16x16/apps/webcamoid.png" },
 }

 local menuee69799670a33f75d45c57d1d1cd0ab3 = {
     {"AdoptOpenJDK Java 11 Console", "/usr/lib/jvm/java-11-adoptopenjdk/bin/jconsole"},
     {"AdoptOpenJDK Java 11 Shell", "xterm -e /usr/lib/jvm/java-11-adoptopenjdk/bin/jshell"},
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"BleachBit", "bleachbit", "/usr/share/pixmaps/bleachbit.png" },
     {"Bulk Rename", "thunar --bulk-rename ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.thunar.png" },
     {"File Manager PCManFM", "pcmanfm ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"Firetools", "firetools", "/usr/share/pixmaps/firetools.png" },
     {"GParted", "/usr/bin/gparted ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"GSmartControl", "/usr/bin/gsmartcontrol_polkit", "/usr/share/icons/hicolor/16x16/apps/gsmartcontrol.png" },
     {"Guake Terminal", "guake", "/usr/share/pixmaps/guake.png" },
     {"Hardware Locality lstopo", "lstopo"},
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
     {"MEGAsync", "megasync", "/usr/share/icons/hicolor/16x16/apps/mega.png" },
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"OpenJDK Java 11 Console", "/usr/lib/jvm/java-11-openjdk/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/java11-openjdk.png" },
     {"OpenJDK Java 11 Shell", "xterm -e /usr/lib/jvm/java-11-openjdk/bin/jshell", "/usr/share/icons/hicolor/16x16/apps/java11-openjdk.png" },
     {"OpenJDK Java 15 Console", "/usr/lib/jvm/java-15-openjdk/bin/jconsole"},
     {"OpenJDK Java 15 Shell", "xterm -e /usr/lib/jvm/java-15-openjdk/bin/jshell"},
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"QDirStat", "qdirstat "},
     {"R-Linux", "rlinux", "/usr/share/pixmaps/rtt-rlinux.png" },
     {"Thunar File Manager", "thunar ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.thunar.png" },
     {"Tint2", "tint2"},
     {"URXVTConfig", "urxvtconfig", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"VeraCrypt", "veracrypt", "/usr/share/pixmaps/veracrypt.xpm" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"conky", "conky --daemonize --pause=1"},
     {"dconf Editor", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/ca.desrt.dconf-editor.png" },
     {"kitty", "kitty", "/usr/share/icons/hicolor/256x256/apps/kitty.png" },
     {"multibootusb", "multibootusb-pkexec", "/usr/share/pixmaps/multibootusb.png" },
 }

xdgmenu = {
    {"Accessibility", menue0e4fc6213e8b3593495a7260c3a4c2e},
    {"Accessories", menu98edb85b00d9527ad5acebe451b3fae6},
    {"Archlinux", menu78059f1898ed518c6ccd6a6392fa82c1},
    {"Education", menude7a22a0c94aa64ba2449e520aa20c99},
    {"Games", menu251bd8143891238ecedc306508e29017},
    {"Graphics", menud334dfcea59127bedfcdbe0a3ee7f494},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Office", menudf814135652a5a308fea15bff37ea284},
    {"Other", menu6311ae17c1ee52b36e68aaf4ad066387},
    {"Programming", menue6f43c40ab1c07cd29e4e83e4ef6bf85},
    {"Science & Math", menu80d754c83abbbd4ef5d150904efcc86c},
    {"Sound & Video", menu52dd1c847264a75f400961bfb4d1c849},
    {"System Tools", menuee69799670a33f75d45c57d1d1cd0ab3},
}
